if SERVER then
    resource.AddFile("sound/tdmrp/headshot.wav")
    resource.AddFile("sound/tdmrp/skills/berserk1.wav")
    resource.AddFile("sound/tdmrp/skills/invincibility1.wav")
    resource.AddFile("sound/tdmrp/skills/healingaura1.wav")
    resource.AddFile("sound/tdmrp/skills/speed1.wav")
    resource.AddFile("sound/tdmrp/skills/regeneration.mp3")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew1.wav")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew2.wav")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew3.wav")
    resource.AddFile("sound/tdmrp/skills/quaddamage1.wav")
    resource.AddFile("sound/tdmrp/skills/quaddamageshootsound.wav")
    resource.AddFile("sound/tdmrp/bodysounds/dink.wav")
    resource.AddFile("sound/tdmrp/quake/dominating.mp3")
    resource.AddFile("sound/tdmrp/quake/doublekill.mp3")
    resource.AddFile("sound/tdmrp/quake/godlike.mp3")
    resource.AddFile("sound/tdmrp/quake/holyshit.mp3")
    resource.AddFile("sound/tdmrp/quake/impressive.mp3")
    resource.AddFile("sound/tdmrp/quake/killingspree.mp3")
    resource.AddFile("sound/tdmrp/quake/monsterkill.mp3")
    resource.AddFile("sound/tdmrp/quake/triplekill.mp3")
    resource.AddFile("sound/tdmrp/quake/ultrakill.mp3")
    resource.AddFile("sound/tdmrp/quake/hitsound.mp3")
    resource.AddFile("sound/tdmrp/quake/newhitsound1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofdoubleshot1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofshrapnel.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofchainlightning1.mp3")
    resource.AddFile("materials/suffixmat/steel_normal.vmt")
    resource.AddFile("sound/physics/metal/metal_impact_hard1.wav") 
    resource.AddFile("sound/physics/metal/metal_impact_hard2.wav")
    resource.AddFile("sound/physics/metal/metal_impact_hard3.wav")
    
    -- Human pain sounds (HL2 male)
    resource.AddFile("sound/npc/player/vo/pain1.wav")
    resource.AddFile("sound/npc/player/vo/pain2.wav")
    resource.AddFile("sound/npc/player/vo/pain3.wav")
    resource.AddFile("sound/npc/player/vo/pain4.wav")
    resource.AddFile("sound/npc/player/vo/pain5.wav")
    resource.AddFile("sound/npc/player/vo/pain6.wav")
    
    -- Humanoid pain sounds (Combine Metro Cop)
    resource.AddFile("sound/npc/metropolice/pain1.wav")
    resource.AddFile("sound/npc/metropolice/pain2.wav")
    resource.AddFile("sound/npc/metropolice/pain3.wav")
    resource.AddFile("sound/npc/metropolice/pain4.wav")
    
    -- CSS Scope overlay materials
    resource.AddFile("materials/scope/scope_normal.vmt")
    resource.AddFile("materials/scope/scope_normal.vtf")
    
    print("[TDMRP] Added skill sounds and scope materials to FastDL/resources.")
    resource.AddWorkshop("2822934109") 
    resource.AddWorkshop("391440832") 
    resource.AddWorkshop("3556711731") 
    resource.AddWorkshop("3485637136")
    resource.AddWorkshop("124565516")
    resource.AddWorkshop("220687225")
    resource.AddWorkshop("128093075")
    resource.AddWorkshop("128089118")
    resource.AddWorkshop("128091208")
    resource.AddWorkshop("466477944")
    resource.AddWorkshop("139247091")
    resource.AddWorkshop("105841291")
    resource.AddWorkshop("730187817")
    resource.AddWorkshop("133613558")
end
