if SERVER then
    resource.AddFile("sound/tdmrp/headshot.wav")
    resource.AddFile("sound/tdmrp/skills/berserk1.wav")
    resource.AddFile("sound/tdmrp/skills/invincibility1.wav")
    resource.AddFile("sound/tdmrp/skills/healingaura1.wav")
    resource.AddFile("sound/tdmrp/skills/speed1.wav")
    resource.AddFile("sound/tdmrp/skills/regeneration.mp3")
    resource.AddFile("sound/tdmrp/skills/blinkmain.mp3")
    resource.AddFile("sound/tdmrp/skills/blinklayer1.mp3")
    resource.AddFile("sound/tdmrp/skills/blinklayer2.mp3")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew1.wav")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew2.wav")
    resource.AddFile("sound/tdmrp/slugsounds/slugshotnew3.wav")
    resource.AddFile("sound/tdmrp/skills/quaddamage1.wav")
    resource.AddFile("sound/tdmrp/skills/quaddamageshootsound.wav")
    resource.AddFile("sound/tdmrp/bodysounds/dink.wav")
    resource.AddFile("sound/tdmrp/quake/dominating.mp3")
    resource.AddFile("sound/tdmrp/quake/doublekill.mp3")
    resource.AddFile("sound/tdmrp/quake/godlike.mp3")
    resource.AddFile("sound/tdmrp/quake/holyshit.mp3")
    resource.AddFile("sound/tdmrp/quake/impressive.mp3")
    resource.AddFile("sound/tdmrp/quake/killingspree.mp3")
    resource.AddFile("sound/tdmrp/quake/monsterkill.mp3")
    resource.AddFile("sound/tdmrp/quake/triplekill.mp3")
    resource.AddFile("sound/tdmrp/quake/ultrakill.mp3")
    resource.AddFile("sound/tdmrp/quake/hitsound.mp3")
    resource.AddFile("sound/tdmrp/quake/newhitsound1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofdoubleshot1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofchainlightning1.mp3")
    
    -- Frost Suffix Sounds
    resource.AddFile("sound/tdmrp/suffixsounds/offrost1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/offrost2.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/offrost3.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/offrostdeath.mp3")
    
    -- Momentum Suffix Sound
    resource.AddFile("sound/tdmrp/suffixsounds/ofmomentum.mp3")
    
    -- Shatter Suffix Sounds
    resource.AddFile("sound/tdmrp/suffixsounds/ofshatter1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofshatter2.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/shatterimpact1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/shatterimpact2.mp3")
    
    -- Homing Suffix Sounds
    resource.AddFile("sound/tdmrp/suffixsounds/ofhoming1.mp3")
    resource.AddFile("sound/tdmrp/suffixsounds/ofhoming2.mp3")
    -- (Manhack sounds are built-in HL2: mh_engine_loop1.wav, mh_blade_snick1.wav, grind_flesh1/2.wav)
    
    -- Combat Voice Lines (Cop Kill Confirmed)
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed1.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed2.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed3.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed4.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed5.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copkillconfirmed6.mp3")
    
    -- Combat Voice Lines (Criminal Kill Confirmed)
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed1.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed2.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed3.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed4.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed5.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimkillconfirmed6.mp3")
    
    -- Combat Voice Lines (Cop Enemy Spotted)
    resource.AddFile("sound/tdmrp/cvoice/copenemyspotted1.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copenemyspotted2.mp3")
    resource.AddFile("sound/tdmrp/cvoice/copenemyspotted3.mp3")
    
    -- Combat Voice Lines (Criminal Enemy Spotted)
    resource.AddFile("sound/tdmrp/cvoice/crimenemyspotted1.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimenemyspotted2.mp3")
    resource.AddFile("sound/tdmrp/cvoice/crimenemyspotted3.mp3")
    
    resource.AddFile("materials/suffixmat/steel_normal.vmt")
    resource.AddFile("materials/suffixmat/frost_ice_shader.vmt")
    
    -- M9K/CSS Scope Materials (ACOG, MilDot, etc.)
    resource.AddFile("materials/scope/gdcw_scopesight.vmt")
    resource.AddFile("materials/scope/gdcw_scopesight.vtf")
    resource.AddFile("materials/scope/gdcw_closedsight.vmt")
    resource.AddFile("materials/scope/gdcw_closedsight.vtf")
    resource.AddFile("materials/scope/gdcw_acogchevron.vmt")
    resource.AddFile("materials/scope/gdcw_acogchevron.vtf")
    resource.AddFile("materials/scope/gdcw_acogcross.vmt")
    resource.AddFile("materials/scope/gdcw_acogcross.vtf")
    resource.AddFile("materials/scope/gdcw_svdsight.vmt")
    resource.AddFile("materials/scope/gdcw_svdsight.vtf")
    resource.AddFile("materials/scope/gdcw_parabolicsight.vmt")
    resource.AddFile("materials/scope/gdcw_parabolicsight.vtf")
    resource.AddFile("materials/scope/gdcw_elcanreticle.vmt")
    resource.AddFile("materials/scope/gdcw_elcanreticle.vtf")
    resource.AddFile("materials/scope/gdcw_elcansight.vmt")
    resource.AddFile("materials/scope/gdcw_elcansight.vtf")
    resource.AddFile("materials/scope/aimpoint.vmt")
    resource.AddFile("materials/scope/aimpoint.vtf")
    resource.AddFile("sound/physics/metal/metal_impact_hard1.wav") 
    resource.AddFile("sound/physics/metal/metal_impact_hard2.wav")
    resource.AddFile("sound/physics/metal/metal_impact_hard3.wav")
    
    -- Human pain sounds (HL2 male)
    resource.AddFile("sound/npc/player/vo/pain1.wav")
    resource.AddFile("sound/npc/player/vo/pain2.wav")
    resource.AddFile("sound/npc/player/vo/pain3.wav")
    resource.AddFile("sound/npc/player/vo/pain4.wav")
    resource.AddFile("sound/npc/player/vo/pain5.wav")
    resource.AddFile("sound/npc/player/vo/pain6.wav")
    
    -- Humanoid pain sounds (Combine Metro Cop)
    resource.AddFile("sound/npc/metropolice/pain1.wav")
    resource.AddFile("sound/npc/metropolice/pain2.wav")
    resource.AddFile("sound/npc/metropolice/pain3.wav")
    resource.AddFile("sound/npc/metropolice/pain4.wav")
    
    -- CSS Scope overlay materials
    resource.AddFile("materials/scope/scope_normal.vmt")
    resource.AddFile("materials/scope/scope_normal.vtf")
    
    print("[TDMRP] Added skill sounds and scope materials to FastDL/resources.")
    resource.AddWorkshop("2822934109") 
    resource.AddWorkshop("391440832") 
    resource.AddWorkshop("3556711731") 
    resource.AddWorkshop("3485637136")
    resource.AddWorkshop("124565516")
    resource.AddWorkshop("220687225")
    resource.AddWorkshop("128093075")
    resource.AddWorkshop("128089118")
    resource.AddWorkshop("128091208")
    resource.AddWorkshop("466477944")
    resource.AddWorkshop("139247091")
    resource.AddWorkshop("105841291")
    resource.AddWorkshop("730187817")
    resource.AddWorkshop("133613558")
end
